module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🧩', '🍉', '💜', '🌸', '🪴', '💊', '💫', '🍂', '🌟', '🎋', '😶‍🌫️', '🫀', '🧿', '👀', '😘', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💗'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://chat.whatsapp.com/FKWqryiBvT91TYJlYEaxwe',
   ',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://i.postimg.cc/fbLksDqz/Screenshot-20251005-224142-Whats-App-Business.jpg',
    NEWSLETTER_JID: '120363398106360290@newsletter',
    NEWSLETTER_MESSAGE_ID: '5775',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: 'queen-ropa,
    OWNER_NAME: 'sanchotech,
    OWNER_NUMBER: '263780325289',
    BOT_VERSION: '1.0.0 ʙᴇᴛᴀ',
    BOT_FOOTER: '> © 𝚙𝚘𝚠𝚎𝚛𝚎𝚍 𝚋𝚢 sanchotech,
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029VbBE7xbFCCoTEjmgV73v'
};
